[package]
name = "example"
version = "0.0.0"
authors = ["zhuxiujia <zhuxiujia@qq.com>"]
edition = "2018"
publish = false


[dependencies]
cogo = {path = "../"}
generator = "0.7"
bytes = "1.0"
serde = { version = "1", features = ["derive"] }
docopt = "1.0"
tempdir = "0.3"
httparse = "1.1"
serde_derive = "1.0"
serde_json = "1"
native-tls="0.2"
tungstenite="0.16"

[[bin]]
name = "channel"
path = "src/channel.rs"

[[bin]]
name = "cqueue"
path = "src/cqueue.rs"

[[bin]]
name = "echo"
path = "src/echo.rs"

[[bin]]
name = "echo_client"
path = "src/echo_client.rs"

[[bin]]
name = "echo_udp"
path = "src/echo_udp.rs"

[[bin]]
name = "echo_udp_client"
path = "src/echo_udp_client.rs"

[[bin]]
name = "echo_udp_client1"
path = "src/echo_udp_client1.rs"

[[bin]]
name = "gen"
path = "src/gen.rs"

[[bin]]
name = "general_io"
path = "src/general_io.rs"

[[bin]]
name = "http"
path = "src/http.rs"

[[bin]]
name = "http-tiny"
path = "src/http-tiny.rs"

[[bin]]
name = "https"
path = "src/https.rs"

[[bin]]
name = "scoped"
path = "src/scoped.rs"

[[bin]]
name = "select"
path = "src/select.rs"

[[bin]]
name = "single_thread_schedule"
path = "src/single_thread_schedule.rs"

[[bin]]
name = "sleep"
path = "src/sleep.rs"

[[bin]]
name = "spawn"
path = "src/spawn.rs"

[[bin]]
name = "websocket"
path = "src/websocket.rs"

[[bin]]
name = "waitgroup"
path = "src/wait_group.rs"

[[bin]]
name = "defer"
path = "src/defer.rs"

[[bin]]
name = "sync_map"
path = "src/sync_map.rs"

[[bin]]
name = "time"
path = "src/time.rs"

[[bin]]
name = "lazy"
path = "src/lazy.rs"

[[bin]]
name = "time_tick"
path = "src/time_tick.rs"

[[bin]]
name = "go"
path = "src/go.rs"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1